In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
arr1

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [3]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:

arr2 = np.ones((4,4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
arr5 = np.identity(5)
arr5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
arr6 = np.arange(10,20)## creates only one dimension array
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
arr7 = np.linspace(10,20,6)#group devied the number ...6....
arr7


array([10., 12., 14., 16., 18., 20.])

In [17]:
arr8 = np.copy(arr3) #copy 
arr8


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
print(arr1)
arr1.shape
